### ISSUE TITLE
Uploading collection artwork

### ISSUE THREAD

**Issue by Septan** [ShaneIsrael/plex-auto-genres#20]
```
D:\github\plex-auto-genres-master\plex-auto-genres-master>python plex-auto-genres.py --library Movies --type standard-movie --set-posters

Connecting to Plex...

You are about to update your [Movies] collection's posters to any matching image titles located at posters/.
[93mContinue? y/n... [0my

Uploading collection artwork...
Traceback (most recent call last):
  File "D:\github\plex-auto-genres-master\plex-auto-genres-master\plex-auto-genres.py", line 35, in <module>
    uploadCollectionArt(plex)
  File "D:\github\plex-auto-genres-master\plex-auto-genres-master\src\plex.py", line 207, in uploadCollectionArt
    + sub(f'^{os.getcwd()}', '', posterPath) + f'{bcolors.ENDC}.')
  File "C:\Python39\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Python39\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Python39\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Python39\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Python39\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Python39\lib\sre_parse.py", line 525, in _parse
    code = _escape(source, this, state)
  File "C:\Python39\lib\sre_parse.py", line 426, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \g at position 3
```

**Comment by ShaneIsrael** [comment]
What version of Python are you running this with?

**Comment by ShaneIsrael** [comment]
Tested the same command with the latest Python 3 version as well as the latest plexapi and I am unable to recreate this issue.
Python 3.9.1
plexapi 4.4.1

**Comment by Septan** [comment]
Python 3.9.2

**Comment by ShaneIsrael** [comment]
Fixed uploading collection artwork on Windows in commit: 3ab94b5bfbb4cd720e248c268da335cce091c3ff
