### ISSUE TITLE
collection sort

### ISSUE THREAD

**Issue by Septan** [ShaneIsrael/plex-auto-genres#21]
```
D:\github\plex-auto-genres-master\plex-auto-genres-master>python plex-auto-genres.py --library Movies --type standard-movie --sort

Connecting to Plex...

You are about to sort [Movies] collection's by prefixing their sort titles with our prefix character set in config/config.json.
[93mContinue? y/n... [0my
Traceback (most recent call last):
  File "D:\github\plex-auto-genres-master\plex-auto-genres-master\plex-auto-genres.py", line 40, in <module>
    sortCollections(plex, LIBRARY)
  File "D:\github\plex-auto-genres-master\plex-auto-genres-master\src\plex.py", line 225, in sortCollections
    collections = plex.library.section(library).collections(title=c)
AttributeError: 'MovieSection' object has no attribute 'collections'
```

**Comment by ShaneIsrael** [comment]
Tested the same command with the latest Python 3 version as well as the latest plexapi and I am unable to recreate this issue.
Python 3.9.1
plexapi 4.4.1

It seems you are on Windows, are you sure your python path is using Python 3 and not Python 2.7? Could also be due to an old version of plexapi that you already had installed. 

`python -m pip install plexapi -U` should upgrade it to the latest version.

**Comment by Septan** [comment]
I was already using plexapi 4.4.1 and python 3.9.2

**Comment by ShaneIsrael** [comment]
I was able to run the latest code with a fresh install of python on Windows 10. There must be something wrong in your windows environment. I would check your python path variables or maybe try using powershell instead of command prompt. 

![image](https://user-images.githubusercontent.com/1677199/111533002-e88f9700-872b-11eb-88d5-15939590a559.png)

**Comment by ShaneIsrael** [comment]
One other thing to check which may be why your seeing that error is to make sure you actually have Collections created under your Movies library in Plex. 

If you run plex-auto-genres without the --sort option it should go through and create collections for your library. Then once those collections are made, you can run the sort command. But if you already have existing collections in your Movies library I'm not sure what else could be the problem other than something with your Windows python install.
