### ISSUE TITLE
Crash with --set-posters

### ISSUE THREAD

**Issue by vaparr** [ShaneIsrael/plex-auto-genres#7]
Getting this issue when trying to set posters:

root@Unraid:/tmp/plex-auto-genres# python3 ./plex-auto-genres.py --library Anime --type anime --set-posters

Connecting to Plex...

You are about to update your [Anime] collection's posters to any matching image titles located at posters/.
Continue? y/n... y

Uploading collection artwork...
Traceback (most recent call last):
  File "./plex-auto-genres.py", line 14, in <module>
    uploadCollectionArt(plex)
  File "/tmp/plex-auto-genres/src/plex.py", line 129, in uploadCollectionArt
    title = sub(f'^{PLEX_COLLECTION_PREFIX}', '', c.title)
  File "/usr/lib64/python3.8/re.py", line 208, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib64/python3.8/re.py", line 302, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib64/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib64/python3.8/sre_parse.py", line 668, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 1

PLEX_COLLECTION_PREFIX = "*"

**Comment by ShaneIsrael** [comment]
Hey thanks for reporting that. I just pushed up a fix so if you pull down the latest changes and try again it should work. Please let me know if the issue is resolved.

**Comment by vaparr** [comment]
Yep! Works now! thanks!
